-- 코드를 입력하세요
    SELECT BK.CATEGORY
         , SUM(SALES)   TOTAL_SALES
      FROM BOOK         BK
INNER JOIN BOOK_SALES   BKS
        ON BKS.BOOK_ID  = BK.BOOK_ID
     WHERE DATE_FORMAT(BKS.SALES_DATE, '%Y-%m') = '2022-01'
  GROUP BY BK.CATEGORY
  ORDER BY BK.CATEGORY