-- 코드를 입력하세요
    SELECT PD.PRODUCT_CODE
         , PD.PRICE * SUM(OS.SALES_AMOUNT)   SALES
      FROM PRODUCT          PD
INNER JOIN OFFLINE_SALE     OS
        ON OS.PRODUCT_ID    = PD.PRODUCT_ID
  GROUP BY PD.PRODUCT_CODE
  ORDER BY SALES DESC
         , PRODUCT_CODE